const path = require('node:path')
const storeConfig = require('./discovery.config')
const { buildI18nDomains } = require('./scripts/i18n')

// Load locales settings (generated by CLI during build)
const localesSettings = storeConfig.localization

const getRootFolder = () => {
  if (__dirname.endsWith('.faststore')) return path.join(__dirname, '..')

  return path.join(__dirname, '../../')
}

console.log(`
  Root folder at: ${getRootFolder()}
  AccountID: ${storeConfig.api?.storeId ?? 'Unknown'}
  Analytics Enabled: ${storeConfig.analytics?.otelEnabled ?? false}
`)

/**
 * @type {import('next').NextConfig}
 * */
const nextConfig = {
  /* config options here */
  /* Replaces terser by swc for minifying. It's the default in NextJS 13 */
  swcMinify: true,
  ...(Array.isArray(storeConfig.experimental?.transpilePackages) &&
    storeConfig.experimental.transpilePackages.length > 0 && {
      transpilePackages: storeConfig.experimental.transpilePackages,
    }),
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: `${storeConfig.api.storeId}.vtexassets.com`,
        pathname: '/**',
      },
    ],
    deviceSizes: [360, 412, 540, 768, 1280, 1440],
    imageSizes: [34, 68, 154, 320],
    loader: 'custom',
    loaderFile: './src/components/ui/Image/loader.ts',
  },
  i18n: localesSettings.enabled
    ? {
        locales: Object.keys(localesSettings.locales || {}),
        defaultLocale: localesSettings.defaultLocale,
        localeDetection: false,
        domains: buildI18nDomains(localesSettings),
      }
    : {
        locales: [storeConfig.session.locale],
        defaultLocale: storeConfig.session.locale,
      },
  sassOptions: {
    silenceDeprecations: ['if-function', 'legacy-js-api'],
  },
  // TODO: We won't need to enable this experimental feature when migrating to Next.js 13
  experimental: {
    instrumentationHook: true,
    scrollRestoration: !storeConfig.experimental.scrollRestoration,
  },
  /*
   * Keep the OpenTelemetry diagnostics packages as server-side runtime externals
   * instead of bundling them. They are server-only OTel libraries that rely on
   * dynamic require() (via require-in-the-middle) and optional instrumentations
   * that are not always installed (e.g. Koa/Nest/Fastify). Bundling them makes
   * webpack emit "Module not found" / "Critical dependency" warnings even though
   * telemetry is gated at runtime by `analytics.otelEnabled`. Externalizing lets
   * Node require them normally at runtime, matching Next.js guidance for OTel.
   */
  serverExternalPackages: [
    '@faststore/diagnostics',
    '@vtex/diagnostics-nodejs',
  ],
  /*
   * The FastStore Discovery CLI will update this value to match the path where the
   * command is being run, because that is where the node_modules directory is.
   * For discovery-only paths, that is the user directory, and for monorepo, that is the base
   * of the monorepo
   * */
  outputFileTracingRoot: getRootFolder(),
  webpack: (config, { isServer, dev }) => {
    // Ignore the benign "Critical dependency: the request of a dependency is an
    // expression" warning from require-in-the-middle inside the OpenTelemetry
    // instrumentation core. It is dynamic require() code webpack cannot analyze
    // statically; the request is resolved at runtime. Pairs with the
    // serverExternalPackages entry above, which removes the "Module not found"
    // warnings for the diagnostics packages.
    config.ignoreWarnings = [
      ...(config.ignoreWarnings || []),
      { module: /@opentelemetry[\\/]instrumentation/ },
      { module: /require-in-the-middle/ },
      { module: /@vtex[\\/]diagnostics-nodejs/ },
    ]

    // https://github.com/vercel/next.js/discussions/11267#discussioncomment-2479112
    // camel-case style names from css modules
    config.module.rules
      .find(({ oneOf }) => !!oneOf)
      .oneOf.filter(({ use }) => JSON.stringify(use)?.includes('css-loader'))
      .reduce((acc, { use }) => acc.concat(use), [])
      .forEach(({ options }) => {
        if (options.modules) {
          options.modules.exportLocalsConvention = 'camelCase'
        }
      })

    // Reduce the number of chunks so we ship a smaller first bundle.
    // This should help reducing TBT
    if (!isServer && !dev && config.optimization?.splitChunks) {
      config.optimization.splitChunks.maxInitialRequests = 1
    }

    return config
  },
  redirects: storeConfig.redirects,
  rewrites: storeConfig.rewrites,
  turbopack: {
    root: getRootFolder(),
    // https://nextjs.org/docs/app/api-reference/turbopack#css-module-ordering
    resolveAlias: {
      '~*': '*',
    },
  },
}

module.exports = nextConfig
